services:
  db:
    image: mysql:8.4
    container_name: study-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # 初期SQLを使いたいなら下をON（任意）
      # - ./study-db/mysql/init:/docker-entrypoint-initdb.d

volumes:
  db_data:
